sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  # Setup virtual framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Install coverage dependencies
  - pip install coverage coveralls
  # Build the docker container
  - pushd $TRAVIS_BUILD_DIR
  - mkdir ~/knowledge-coverage
  - docker build -t test_knowledge .
script:
  - make test
after_success:
  - ls /tmp/knowledge-coverage
  - mv /tmp/knowledge-coverage/.coverage.* . || echo ok
  - coverage combine
  - coverage report
  - coveralls
